Hotel 11
dudarenko-dmitry/senla_training pull request #17
Opened 2023-11-03 00:22 UTC by dudarenko-dmitry

Task is not finished yet.
It is need to write realization of Read, Update, Delete methods.
Please, could you look over if I understood correctly and implemented here GenericDao pattern?
![image](https://github.com/dudarenko-dmitry/senla_training/assets/102149674/8405528c-5a26-4720-a701-bac2ab26de0b)

2023-11-04 20:16 UTC, Mark005 requested changes

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/connection/AbstractConnection.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
you can call it with new, it doesn't have any differences between calling with new, don't make your code harder

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/dao/GenericDaoDB.java
> +        return (T) new Object();
it will not work, you can't cast object to a specific type

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/dao/GenericDaoDB.java
> +        return true;
??

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/dao/GenericDaoDB.java
> +        return true;
if you don't have implementation yet and it should be implemented in extended class then make it abstract

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityImpl.java
>              System.out.println(ERROR_READ_ALL_HOTEL_FACILITY);
why it's an error? it's one of the possible flows of how your program should work

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityImpl.java
> +        if(daoHotelFacility.readAll() == null || daoHotelFacility.readAll().isEmpty()){
why do you read all?? you need only update hotelFacilityString by id (hotelFacilityString - not self-describing, change it), there is only one check you can do here is a check entity in DB that exists by id

2023-11-04 20:16 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityImpl.java
> +        if(daoHotelFacility.readAll() == null || daoHotelFacility.readAll().isEmpty()){
why do you always check db? it's unnecessary

2023-11-05 23:44 UTC, dudarenko-dmitry commented on src/pl/senla/hotel/connection/AbstractConnection.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
do you meen this?
![image](https://github.com/dudarenko-dmitry/senla_training/assets/102149674/76306ed1-f8d9-4587-9520-dd79fbaf0619)
I have seen many examples in internet with Class.forName. Why do they do in such way if it is not nessesery?

2023-11-14 12:29 UTC, Mark005 commented on src/pl/senla/hotel/connection/AbstractConnection.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
it was made to make it more flexible (like it was done in spring boot 
![image](https://github.com/dudarenko-dmitry/senla_training/assets/39222770/cbfe5a35-2b16-472e-a385-4efa50a36355)
) all drivers should implement java.sql.Driver interface so you can switch drives easily only by class name, but in your case it's not necessary I believe

2023-11-14 12:30 UTC, Mark005 commented on src/pl/senla/hotel/connection/AbstractConnection.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
or you can put driver class name in the app props, it's up to you

2023-11-14 12:58 UTC, Mark005 requested changes

2023-11-14 12:58 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityDB.java
> +            return daoHotelFacility.readAll();
put value in a variable and check whatever you need, in your code if something is in db you will make 3 requests to return value

2023-11-14 12:58 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityDB.java
> +        setIdFacilityNew(hotelFacility);
get rid of this, your id should be generated in BD and you have to map it back into your provided entity, OR your csv should already have this ids(should be exported with ids)

2023-11-14 12:58 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceFacilityDB.java
> +        if(daoHotelFacility.read(idFacility) != null){
same here, two requests instead of 1

2023-11-14 12:58 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceHotelServiceDB.java
> +            case "RoomReservation" -> serviceRoomReservation.create(hotelServiceString);
do you still need this switch?

2023-11-14 12:58 UTC, Mark005 commented on src/pl/senla/hotel/service/ServiceHotelServiceDB.java
> +                case "RoomReservation" -> serviceRoomReservation.update(idHotelService, hotelServiceString);
same here

2023-11-14 17:08 UTC, dudarenko-dmitry commented on src/pl/senla/hotel/service/ServiceHotelServiceDB.java
> +            case "RoomReservation" -> serviceRoomReservation.create(hotelServiceString);
it's not needed today.
only for further development of application

2023-11-16 22:26 UTC, Mark005 approved these changes

2023-11-16 22:58 UTC, merged